# Generated by Django 2.0.6 on 2018-07-19 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180605_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_file',
            field=models.FileField(blank=True, null=True, upload_to='bank/problem_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
