# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trial', '0003_auto_20170728_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.Problem', verbose_name='problem')),
            ],
            options={
                'ordering': ['problem_id'],
                'verbose_name': 'Contest Problem',
            },
        ),
    ]
