# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='testcase_codes',
            field=models.CharField(default='[-1]', max_length=100, verbose_name='Testcase Status Code'),
        ),
    ]
