# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_auto_20170728_2227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='submitted-by IP')),
                ('local_file', models.CharField(max_length=150, null=True, verbose_name='Original File')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trial.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='submitted-by')),
            ],
        ),
    ]
