# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170715_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Contest Problem'},
        ),
    ]
