# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='submitted-by (IP)'),
        ),
    ]
