# Generated by Django 2.0.6 on 2018-06-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20180103_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-time']},
        ),
    ]
