# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='output',
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.CharField(max_length=3000),
        ),
    ]
