# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_auto_20170722_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(max_length=3000),
        ),
    ]
